### PR TITLE
Add zh-TW locale

### PR DESCRIPTION
**Pull request by frozenfung**

### CODE REVIEW

**Comment by frozenfung** [comment]
Just don't know why my PR exploded suddenly.
Reopen it with correct syntax :P

**Comment by DarthSim** [comment]
Awesome, merged :+1:

**Comment by DarthSim** [comment]
@frozenfung I added a new string to I18n. Could you check zh-TW locale?

**Comment by frozenfung** [comment]
Just create a PR for this.

**Pull request merged**
